apiVersion: apps/v1
kind: Deployment
metadata:
  name: googlegrocery-deployment
  labels:
    app: googlegrocery
spec:
  replicas: 2
  selector:
    matchLabels:
      app: googlegrocery
  template:
    metadata:
      labels:
        app: googlegrocery
    spec:
      containers:
      - name: googlegrocery
        image: 004657932016.dkr.ecr.us-east-1.amazonaws.com/shopping-site-googlegrocery:2f106fde08828b8d906729c7fff58a50a8755938
        ports:
        - containerPort: 80
